### ISSUE TITLE
Not building on current version

### ISSUE THREAD

**Issue by seand88** [rroylance/phaser-npm-webpack-typescript-starter-project#20]
trying to build the project after download the zip file.
Getting this error

npm run server:dev
```
fatal: Not a git repository (or any of the parent directories): .git
child_process.js:518
    throw err;
    ^

Error: Command failed: git rev-parse HEAD
fatal: Not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:475:13)
    at execSync (child_process.js:515:13)
    at module.exports (/Users/keenan/development/lastlight/node_modules/git-revision-webpack-plugin/lib/helpers/run-git-command.js:25:34)
    at GitRevisionPlugin.commithash (/Users/keenan/development/lastlight/node_modules/git-revision-webpack-plugin/lib/index.js:42:10)
    at Object.<anonymous> (/Users/keenan/development/lastlight/webpack.dev.config.js:29:68)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/keenan/development/lastlight/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/keenan/development/lastlight/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (/Users/keenan/development/lastlight/node_modules/webpack/bin/convert-argv.js:107:15)
```

**Comment by rroylance** [comment]
Sorry about that. All you need to do is open up the webpack config files and remove the like at the top for the git revision plugin and the liNe in the DefinePlugin for GIT_REVISION and then in boot.ts remove the console log for GIT_REVISION. I'm going to remove all that tomorrow, it was not a good choice to have that in in the first place, not all people will be using it from a git repo...

**Comment by SgtPooki** [comment]
I'm not sure if you changed this in the last hour or so.. but it builds fine for me. The only problem I have is that the webfonts don't load on first page load, so it throws an error at assetUtils.js:131 that 
``` Assets.BitmapFonts[font][imageOption]() is not a function ```

after adding a debugger statement, then reloading the page, it loaded up fine.

**Comment by rroylance** [comment]
@seand88 1.7.10 removes the dependency on GIT. Sorry about that.

@SgtPooki I would consider that just a cache thing. Probably clearing your cache and re-running would have fixed it as well.
